github:
  application:
    client-id: // OAuth Apps
    client-secret: // OAuth Apps
    callback: // OAuth Apps
    scope-user: user
    scope-email: emails
google:
  application:
    client-id: // Firebase Authentication
    client-secret: // Firebase Authentication
    callback: // Firebase Authentication
    scope-profile: https://www.googleapis.com/auth/userinfo.profile
    scope-email: https://www.googleapis.com/auth/userinfo.email

spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  mvc:
    converters:
      preferred-json-mapper: gson
  datasource:
    default-time-zone:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://www.def-v.com
    username: // ****
    password: // ****
server:
  port: // 0000
  ssl:
    key-store: // keystore.p12
    key-store-password: // ****
    key-store-type: PKCS12
    key-alias: tomcat

spring-boot:
  formatted-version: 1.0
